In [1]:
import numpy as np

print(np.__version__)

2.4.4

In [2]:
import matplotlib

print(matplotlib.__version__)

3.10.9

In [3]:
import pandas as pd

print(pd.__version__)

3.0.2

In [4]:
import sys

print("Python version:", sys.version)

Python version: 3.12.13 | packaged by Anaconda, Inc. | (main, Mar 19 2026, 20:16:45) [MSC v.1942 64 bit (AMD64)]

In [5]:
def create_student_data():
    # Student IDs
    ids = np.array([1, 2, 3, 4, 5])

    # Minimum/pass marks
    min_marks = np.array([40, 40, 40, 40, 40])

    # Final marks
    final_marks = np.array([75, 35, 60, 90, 38])

    # Result
    result = np.where(final_marks >= min_marks, "Pass", "Fail")

    return ids, min_marks, final_marks, result

In [6]:
# Call the function
ids, min_marks, final_marks, result = create_student_data()

print("ID:", ids)
print("Min Marks:", min_marks)
print("Final Marks:", final_marks)
print("Result:", result)

ID: [1 2 3 4 5]
Min Marks: [40 40 40 40 40]
Final Marks: [75 35 60 90 38]
Result: ['Pass' 'Fail' 'Pass' 'Pass' 'Fail']

In [7]:
from scipy import stats

In [11]:
import numpy as np

def create_student():
    
    # Same random data every time (optional)
    np.random.seed(42)
    
    n = 50
    
    # Student IDs from 1 to 50
    student_id = np.arange(1, 51)
    
    # Random student names
    names = np.random.choice([
        "Shobhit", "Sanjiv", "aashutoh", "ashok",
        "Ram", "Hari", "Sita", "Gita",
        "Ramesh", "Bikash"
    ], n)
    
    # Random age
    age = np.random.randint(18, 26, n)
    
    # Random study hours
    study_hours = np.random.randint(1, 11, n)
    
    # Random midterm score
    midterm_score = np.random.randint(0, 51, n)
    
    # Random final score
    final_score = np.random.randint(0, 51, n)
    
    # Random attendance percentage
    attendance = np.random.randint(50, 101, n)
    
    # Random campus
    campus = np.random.choice(
        ["Kathmandu", "Bhaktapur", "Lalitpur"],
        n
    )
    
    return {
        "Student ID": student_id,
        "Name": names,
        "Age": age,
        "Study Hours": study_hours,
        "Midterm Score": midterm_score,
        "Final Score": final_score,
        "Attendance": attendance,
        "Campus": campus
    }

In [12]:
# Create dataset
data = create_student()

# Print data
for key, value in data.items():
    print(key, ":", value)

Student ID : [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
Name : ['Sita' 'ashok' 'Gita' 'Ram' 'Sita' 'Bikash' 'aashutoh' 'Sita' 'Gita'
 'Ram' 'ashok' 'Gita' 'Gita' 'aashutoh' 'Hari' 'Ram' 'Sanjiv' 'Gita'
 'Hari' 'Sanjiv' 'Ram' 'Shobhit' 'Bikash' 'Hari' 'Ramesh' 'Shobhit'
 'Bikash' 'aashutoh' 'Sita' 'ashok' 'Ramesh' 'aashutoh' 'Ram' 'aashutoh'
 'Sita' 'Ram' 'Ramesh' 'Sita' 'Sanjiv' 'ashok' 'Ramesh' 'Sanjiv' 'Bikash'
 'Ramesh' 'Bikash' 'Ram' 'Sanjiv' 'ashok' 'Sita' 'Gita']
Age : [24 20 23 18 21 19 25 21 19 23 23 23 19 21 23 22 24 19 19 21 19 19 23 21
 23 24 25 24 25 23 24 21 18 23 25 22 25 22 19 24 22 25 19 18 21 21 21 22
 18 22]
Study Hours : [ 1  9  7  9  8  1  8  8  3  1  8  3  3  1  5 10  7 10  9  7  9  8  2  1
  7  7  8  5  3  8  6  3  1  3  5  3  1  5 10  7  7  9 10 10  3  7  1  4
  4  5]
Midterm Score : [22 38 44 14 42 28 35 12 31  6 50 21 27  1 41 44  5 27 27 43 43 19 29 10
 27 24 38 32  0 26 12 40  2 38  5  7 26  8 36 32 50 41 43 23 14 31 31 23
 40 48]
Final Score : [48 11 38  1  2 48 36 48 16 48  1  1 27 22 36 31 32  0 18  1 43 25 31  5
 31  3 10 16 37 23  4 33  5 21 10 47 15 32  8  5 15 28  2 19 35 18 25  2
 18 19]
Attendance : [81 56 90 82 89 88 67 89 50 60 77 74 99 72 80 79 91 84 56 65 75 97 98 51
 50 97 61 54 86 81 58 90 84 68 97 65 52 69 73 82 73 60 98 57 85 87 89 69
 84 97]
Campus : ['Bhaktapur' 'Kathmandu' 'Lalitpur' 'Kathmandu' 'Kathmandu' 'Bhaktapur'
 'Bhaktapur' 'Bhaktapur' 'Bhaktapur' 'Bhaktapur' 'Lalitpur' 'Kathmandu'
 'Kathmandu' 'Kathmandu' 'Kathmandu' 'Bhaktapur' 'Kathmandu' 'Lalitpur'
 'Lalitpur' 'Kathmandu' 'Kathmandu' 'Lalitpur' 'Lalitpur' 'Bhaktapur'
 'Lalitpur' 'Bhaktapur' 'Bhaktapur' 'Bhaktapur' 'Bhaktapur' 'Bhaktapur'
 'Kathmandu' 'Lalitpur' 'Bhaktapur' 'Lalitpur' 'Lalitpur' 'Bhaktapur'
 'Kathmandu' 'Bhaktapur' 'Kathmandu' 'Lalitpur' 'Kathmandu' 'Kathmandu'
 'Kathmandu' 'Lalitpur' 'Lalitpur' 'Kathmandu' 'Kathmandu' 'Bhaktapur'
 'Kathmandu' 'Bhaktapur']

In [13]:
import pandas as pd

df = pd.DataFrame(data)

df.head()

,Student ID,Name,Age,Study Hours,Midterm Score,Final Score,Attendance,Campus
0,1,Sita,24,1,22,48,81,Bhaktapur
1,2,ashok,20,9,38,11,56,Kathmandu
2,3,Gita,23,7,44,38,90,Lalitpur
3,4,Ram,18,9,14,1,82,Kathmandu
4,5,Sita,21,8,42,2,89,Kathmandu

In [ ]:

df.info(memory_usage="deep")

2332
<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Student ID     50 non-null     int64
 1   Name           50 non-null     str
 2   Age            50 non-null     int32
 3   Study Hours    50 non-null     int32
 4   Midterm Score  50 non-null     int32
 5   Final Score    50 non-null     int32
 6   Attendance     50 non-null     int32
 7   Campus         50 non-null     str
dtypes: int32(5), int64(1), str(2)
memory usage: 7.0 KB

In [16]:
df.describe()

,Student ID,Age,Study Hours,Midterm Score,Final Score,Attendance
count,50.00000,50.000000,50.000000,50.000000,50.000000,50.000000
mean,25.50000,21.700000,5.600000,27.120000,21.000000,76.320000
std,14.57738,2.215437,3.043897,14.181966,15.150941,14.948128
min,1.00000,18.000000,1.000000,0.000000,0.000000,50.000000
25%,13.25000,19.250000,3.000000,15.250000,5.750000,65.000000
50%,25.50000,22.000000,6.500000,27.500000,19.000000,79.500000
75%,37.75000,23.000000,8.000000,39.500000,32.000000,88.750000
max,50.00000,25.000000,10.000000,50.000000,48.000000,99.000000

In [23]:
memory = df.memory_usage().sum()
print(memory)

memory_mb = memory / (1024 * 1024)

print("Memory used:", memory_mb, "MB")

2332
Memory used: 0.002223968505859375 MB

In [22]:
print(df.memory_usage().sum())

2332

In [24]:
print(df.dtypes)

Student ID       int64
Name               str
Age              int32
Study Hours      int32
Midterm Score    int32
Final Score      int32
Attendance       int32
Campus             str
dtype: object

In [27]:
print(df)

    Student ID      Name  Age  Study Hours  Midterm Score  Final Score  \
0            1      Sita   24            1             22           48
1            2     ashok   20            9             38           11
2            3      Gita   23            7             44           38
3            4       Ram   18            9             14            1
4            5      Sita   21            8             42            2
5            6    Bikash   19            1             28           48
6            7  aashutoh   25            8             35           36
7            8      Sita   21            8             12           48
8            9      Gita   19            3             31           16
9           10       Ram   23            1              6           48
10          11     ashok   23            8             50            1
11          12      Gita   23            3             21            1
12          13      Gita   19            3             27           27
13          14  aashutoh   21            1              1           22
14          15      Hari   23            5             41           36
15          16       Ram   22           10             44           31
16          17    Sanjiv   24            7              5           32
17          18      Gita   19           10             27            0
18          19      Hari   19            9             27           18
19          20    Sanjiv   21            7             43            1
20          21       Ram   19            9             43           43
21          22   Shobhit   19            8             19           25
22          23    Bikash   23            2             29           31
23          24      Hari   21            1             10            5
24          25    Ramesh   23            7             27           31
25          26   Shobhit   24            7             24            3
26          27    Bikash   25            8             38           10
27          28  aashutoh   24            5             32           16
28          29      Sita   25            3              0           37
29          30     ashok   23            8             26           23
30          31    Ramesh   24            6             12            4
31          32  aashutoh   21            3             40           33
32          33       Ram   18            1              2            5
33          34  aashutoh   23            3             38           21
34          35      Sita   25            5              5           10
35          36       Ram   22            3              7           47
36          37    Ramesh   25            1             26           15
37          38      Sita   22            5              8           32
38          39    Sanjiv   19           10             36            8
39          40     ashok   24            7             32            5
40          41    Ramesh   22            7             50           15
41          42    Sanjiv   25            9             41           28
42          43    Bikash   19           10             43            2
43          44    Ramesh   18           10             23           19
44          45    Bikash   21            3             14           35
45          46       Ram   21            7             31           18
46          47    Sanjiv   21            1             31           25
47          48     ashok   22            4             23            2
48          49      Sita   18            4             40           18
49          50      Gita   22            5             48           19

    Attendance     Campus
0           81  Bhaktapur
1           56  Kathmandu
2           90   Lalitpur
3           82  Kathmandu
4           89  Kathmandu
5           88  Bhaktapur
6           67  Bhaktapur
7           89  Bhaktapur
8           50  Bhaktapur
9           60  Bhaktapur
10          77   Lalitpur
11          74  Kathmandu
12          99  Kathmandu
13          72  Kathmandu
14          80  Kathmandu
15          79  Bhaktapur
16          91  Kathmandu
17          84   Lalitpur
18          56   Lalitpur
19          65  Kathmandu
20          75  Kathmandu
21          97   Lalitpur
22          98   Lalitpur
23          51  Bhaktapur
24          50   Lalitpur
25          97  Bhaktapur
26          61  Bhaktapur
27          54  Bhaktapur
28          86  Bhaktapur
29          81  Bhaktapur
30          58  Kathmandu
31          90   Lalitpur
32          84  Bhaktapur
33          68   Lalitpur
34          97   Lalitpur
35          65  Bhaktapur
36          52  Kathmandu
37          69  Bhaktapur
38          73  Kathmandu
39          82   Lalitpur
40          73  Kathmandu
41          60  Kathmandu
42          98  Kathmandu
43          57   Lalitpur
44          85   Lalitpur
45          87  Kathmandu
46          89  Kathmandu
47          69  Bhaktapur
48          84  Kathmandu
49          97  Bhaktapur

In [28]:
ramdom_rows = np.random.choice(df.index, size=5, replace= False)
df.loc[ramdom_rows, "Age"] = np.nan
print(df)

    Student ID      Name   Age  Study Hours  Midterm Score  Final Score  \
0            1      Sita  24.0            1             22           48
1            2     ashok  20.0            9             38           11
2            3      Gita  23.0            7             44           38
3            4       Ram  18.0            9             14            1
4            5      Sita  21.0            8             42            2
5            6    Bikash  19.0            1             28           48
6            7  aashutoh  25.0            8             35           36
7            8      Sita  21.0            8             12           48
8            9      Gita  19.0            3             31           16
9           10       Ram  23.0            1              6           48
10          11     ashok  23.0            8             50            1
11          12      Gita   NaN            3             21            1
12          13      Gita  19.0            3             27           27
13          14  aashutoh  21.0            1              1           22
14          15      Hari  23.0            5             41           36
15          16       Ram  22.0           10             44           31
16          17    Sanjiv  24.0            7              5           32
17          18      Gita  19.0           10             27            0
18          19      Hari  19.0            9             27           18
19          20    Sanjiv   NaN            7             43            1
20          21       Ram  19.0            9             43           43
21          22   Shobhit  19.0            8             19           25
22          23    Bikash  23.0            2             29           31
23          24      Hari  21.0            1             10            5
24          25    Ramesh  23.0            7             27           31
25          26   Shobhit  24.0            7             24            3
26          27    Bikash  25.0            8             38           10
27          28  aashutoh   NaN            5             32           16
28          29      Sita  25.0            3              0           37
29          30     ashok  23.0            8             26           23
30          31    Ramesh  24.0            6             12            4
31          32  aashutoh  21.0            3             40           33
32          33       Ram  18.0            1              2            5
33          34  aashutoh  23.0            3             38           21
34          35      Sita  25.0            5              5           10
35          36       Ram  22.0            3              7           47
36          37    Ramesh  25.0            1             26           15
37          38      Sita  22.0            5              8           32
38          39    Sanjiv  19.0           10             36            8
39          40     ashok  24.0            7             32            5
40          41    Ramesh  22.0            7             50           15
41          42    Sanjiv  25.0            9             41           28
42          43    Bikash  19.0           10             43            2
43          44    Ramesh  18.0           10             23           19
44          45    Bikash   NaN            3             14           35
45          46       Ram  21.0            7             31           18
46          47    Sanjiv  21.0            1             31           25
47          48     ashok  22.0            4             23            2
48          49      Sita  18.0            4             40           18
49          50      Gita   NaN            5             48           19

    Attendance     Campus
0           81  Bhaktapur
1           56  Kathmandu
2           90   Lalitpur
3           82  Kathmandu
4           89  Kathmandu
5           88  Bhaktapur
6           67  Bhaktapur
7           89  Bhaktapur
8           50  Bhaktapur
9           60  Bhaktapur
10          77   Lalitpur
11          74  Kathmandu
12          99  Kathmandu
13          72  Kathmandu
14          80  Kathmandu
15          79  Bhaktapur
16          91  Kathmandu
17          84   Lalitpur
18          56   Lalitpur
19          65  Kathmandu
20          75  Kathmandu
21          97   Lalitpur
22          98   Lalitpur
23          51  Bhaktapur
24          50   Lalitpur
25          97  Bhaktapur
26          61  Bhaktapur
27          54  Bhaktapur
28          86  Bhaktapur
29          81  Bhaktapur
30          58  Kathmandu
31          90   Lalitpur
32          84  Bhaktapur
33          68   Lalitpur
34          97   Lalitpur
35          65  Bhaktapur
36          52  Kathmandu
37          69  Bhaktapur
38          73  Kathmandu
39          82   Lalitpur
40          73  Kathmandu
41          60  Kathmandu
42          98  Kathmandu
43          57   Lalitpur
44          85   Lalitpur
45          87  Kathmandu
46          89  Kathmandu
47          69  Bhaktapur
48          84  Kathmandu
49          97  Bhaktapur

In [33]:
df.isnull().sum()

Student ID       0
Name             0
Age              5
Study Hours      0
Midterm Score    0
Final Score      0
Attendance       0
Campus           0
dtype: int64